name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpass

    steps:
      - name: test pg connection
        run: pg_isready -h localhost -p 5432

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build and test
        run: ./mvnw test

  deploy:
    runs-on: ubuntu-latest
    needs: test  # deploy only if tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build app
        run: ./mvnw clean package -DskipTests

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: egglectricity
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar